In [32]:
import numpy as np
arr = np.arange(1,13).reshape(2,2,3) #Create a 3D NumPy array named arr with shape (2, 2, 3) containing integers from 1 to 12.
print(arr) #print array
print()
print(np.ndim(arr), "is the number of dimensions")#Print the number of dimensions (ndim) of arr.

print(arr[1,0,2],"is the extract and print the element at position [1, 0, 2] (layer 1, row 0, column 2)")#Extract and print the element at position [1, 0, 2] (layer 1, row 0, column 2).
print(arr[0,:,:],"To the left we see the entire first layer: arr[0, :, :]")#the entire first layer: arr[0, :, :]
print(arr[:,:,2],"To the left we see the entire third column across all layers and rows")#Extract and print the entire third column across all layers and rows: arr[:, :, 2].
print()
arr[0, 1, :]=99 #Replace the second row of the first layer (arr[0, 1, :]) with [99, 99, 99].
print(arr)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

3 is the number of dimensions
9 is the extract and print the element at position [1, 0, 2] (layer 1, row 0, column 2)
[[1 2 3]
 [4 5 6]] To the left we see the entire first layer: arr[0, :, :]
[[ 3  6]
 [ 9 12]] To the left we see the entire third column across all layers and rows

[[[ 1  2  3]
  [99 99 99]]

 [[ 7  8  9]
  [10 11 12]]]


In [65]:
a = np.zeros(5,)#a = an array of zeros with shape (5,)
print(a)
b = np.ones((3,4), dtype='int32')#b = an array of ones with shape (3, 4) and dtype int32
print(b)
c = np.full((2,3,4),7,dtype='float64') #c = an array full of 7’s with shape (2, 3, 4) and dtype float64
print(c)
result = a + np.full((5,),5)           #Add a and a new array of fives of the same shape as a.
print(result)
result_2 = b*10 #Multiply b by 10.
print(result_2)
square = c**2 #Compute c raised to the power of 2 (element-wise square).
print(square)

[0. 0. 0. 0. 0.]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[7. 7. 7. 7.]
  [7. 7. 7. 7.]
  [7. 7. 7. 7.]]

 [[7. 7. 7. 7.]
  [7. 7. 7. 7.]
  [7. 7. 7. 7.]]]
[5. 5. 5. 5. 5.]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[[49. 49. 49. 49.]
  [49. 49. 49. 49.]
  [49. 49. 49. 49.]]

 [[49. 49. 49. 49.]
  [49. 49. 49. 49.]
  [49. 49. 49. 49.]]]


In [71]:

a = np.ones((2, 3))            # shape (2, 3)
b = np.full((3, 2), 2)         # shape (3, 2)

print(np.matmul(a,b))        #Compute the matrix product of a and b using np.matmul().

m = np.array([[4, 7],
              [2, 6]])
print(np.linalg.det(m))  #Compute the detemrinant
print(np.linalg.inv(m))  #Compute the inverse

[[6. 6.]
 [6. 6.]]
10.000000000000002
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [86]:
#stats on arrays
data = np.array([[1, 5, 9],
                 [2, 6, 10],
                 [3, 7, 11],
                 [4, 8, 12]])
print(data.min(),"is the min of this array")            #Print the overall minimum
print(data.max(),"is the max of this array")            #Print the overall maximum         
print(data.sum(),"is the sum of this array")            #Print the overall sum         
print(np.min(data, axis=0),"is the minimum of each column of this array")    #Print the minimum of each column (axis=0) 
print(np.max(data, axis=0),"is the maxium of each column of this array")     #Print the maximum of each column (axis=0)
print(np.sum(data, axis=1),"is the sum of each row")                         #Print the sum of each row (axis=1).


1 is the max of this array
12 is the min of this array
78 is the sum of this array
[1 5 9] is the minimum of each column of this array
[ 4  8 12] is the maxium of each column of this array
[15 18 21 24] is the sum of each column


In [99]:
#reshaping
data = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(data)
print("The shape now is", data.shape)
print()
reshape = data.reshape(2,4)#Reshape data into a (2,4) array.
print(reshape)
print("The shape now is", reshape.shape)
print()
re_reshape = data.reshape(4,2)#Then reshape it into a (4,2) array.
print(re_reshape)
print("The shape now is",re_reshape.shape)
print()
final_reshape = data.reshape(8,1)
print(final_reshape)
print("The shape now is",final_reshape.shape)

[1 2 3 4 5 6 7 8]
The shape now is (8,)

[[1 2 3 4]
 [5 6 7 8]]
The shape now is (2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
The shape now is (4, 2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
The shape now is (8, 1)


In [110]:
#stacking
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(np.vstack([v1,v2]))          #Vertically stack v1 and v2 to make a 2x3 array.
print()
print(np.hstack([v1,v2]))          #Horizontally stack v1 and v2 to make a 1x6 array.
print()
print(np.vstack([v1,v2,v1,v2]))#Vertically stack v1, v2, v1, and v2 (repeat twice vertically).
print(print("The shape of the above one is:", np.vstack([v1,v2,v1,v2]).shape))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
The shape of the above one is: (4, 3)
None
